/**
 * Generate `src/schemas/generated.ts` from every `specs/schemas/S_*.json`.
 *
 * The output exports one TS type per schema (named after the schema `$id`) and
 * a single `SchemaRegistry` keyed by `$id` mapping to the raw schema document.
 * Downstream code imports both the static type and the runtime registry from
 * one module so type and validator never drift.
 */

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const schemaDir = join(repoRoot, "specs", "schemas");
const outFile = join(repoRoot, "src", "schemas", "generated.ts");

async function main(): Promise<void> {
  const entries = await readdir(schemaDir);
  const schemaFiles = entries.filter((f) => f.startsWith("S_") && f.endsWith(".json")).sort();

  if (schemaFiles.length === 0) {
    throw new Error(`No S_*.json files found in ${schemaDir}`);
  }

  const blocks: string[] = [];
  const registry: Array<{ id: string; file: string }> = [];

  for (const file of schemaFiles) {
    const path = join(schemaDir, file);
    const raw = await readFile(path, "utf8");
    const schema = JSON.parse(raw) as Record<string, unknown>;
    const id = typeof schema.$id === "string" ? schema.$id : file.replace(/\.json$/, "");

    // Inject the schema $id as the title so json-schema-to-typescript names
    // the root interface after the schema id (e.g. `S_assessment`) instead of
    // deriving a PascalCase name from the human-readable title. This keeps
    // the generated TS type names aligned with the spec-canonical IDs that
    // every other artifact references.
    const schemaWithIdTitle = { ...schema, title: id };
    const ts = await compile(schemaWithIdTitle as Parameters<typeof compile>[0], id, {
      bannerComment: "",
      additionalProperties: false,
      style: { semi: true, singleQuote: false },
    });

    blocks.push(`// ── ${id} ──\n${ts.trim()}`);
    registry.push({ id, file });
  }

  // Build import lines and registry entries from discovered schemas
  const importLines = registry
    .map(({ id, file }) => `import _${id} from "../../specs/schemas/${file}" with { type: "json" };`)
    .join("\n");

  const registryEntries = registry
    .map(({ id }) => `  ${id}: _${id},`)
    .join("\n");

  const header = [
    "// AUTO-GENERATED by scripts/build-schema-types.ts — do not edit.",
    "// Source: specs/schemas/*.json",
    "// Run `npm run build:types` to regenerate.",
    "",
    "/* eslint-disable */",
    "",
  ].join("\n");

  const footer = [
    "",
    "// Runtime registry of raw schema JSON, keyed by $id.",
    "// Loaded eagerly so ajv can compile validators without further disk I/O.",
    importLines,
    "",
    "export const SchemaRegistry = {",
    registryEntries,
    "} as const;",
    "",
    "export type SchemaId = keyof typeof SchemaRegistry;",
    "",
    "// Snake-case aliases matching the spec-canonical schema $id values.",
    "// json-schema-to-typescript force-normalises to PascalCase; these aliases",
    "// let callers import either form.",
    ...registry.map(({ id }) => {
      const pascal = id
        .split("_")
        .map((part) => (part.length === 0 ? "" : part[0]!.toUpperCase() + part.slice(1)))
        .join("");
      return `export type ${id} = ${pascal};`;
    }),
    "",
  ].join("\n");

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, header + blocks.join("\n\n") + "\n" + footer);
  // eslint-disable-next-line no-console
  console.log(`Generated ${outFile} from ${schemaFiles.length} schemas.`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
